/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#f0eded",
        primary: "#a73400",
        "surface-bright": "#fcf9f8",
        "primary-fixed": "#ffdbcf",
        "surface-container-low": "#f6f3f2",
        "inverse-surface": "#303030",
        "tertiary-fixed": "#b9efc5",
        tertiary: "#346645",
        "primary-fixed-dim": "#ffb59c",
        "secondary-fixed-dim": "#cec5bb",
        "on-secondary": "#ffffff",
        surface: "#fcf9f8",
        "secondary-fixed": "#ebe1d6",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary-fixed": "#1f1b14",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#eae7e7",
        "on-primary": "#ffffff",
        "on-surface-variant": "#594139",
        background: "#fcf9f8",
        "secondary-container": "#ebe1d6",
        "surface-dim": "#dcd9d9",
        "tertiary-container": "#4d7f5c",
        "on-surface": "#1b1c1c",
        "primary-container": "#cc4911",
        "on-tertiary-container": "#f6fff4",
        "on-primary-fixed": "#390c00",
        "on-tertiary-fixed-variant": "#1e5031",
        "inverse-primary": "#ffb59c",
        "on-tertiary-fixed": "#00210e",
        "surface-container-lowest": "#ffffff",
        error: "#ba1a1a",
        outline: "#8d7168",
        "outline-variant": "#e1bfb4",
        "surface-variant": "#e5e2e1",
        "on-error": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "tertiary-fixed-dim": "#9dd3aa",
        "on-background": "#1b1c1c",
        "on-primary-container": "#fffbff",
        "surface-tint": "#ab3600",
        "on-secondary-fixed-variant": "#4c463e",
        secondary: "#645d55",
        "on-error-container": "#93000a",
        "on-secondary-container": "#6a635b",
        "on-primary-fixed-variant": "#822700",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        "stack-md": "16px",
        "container-margin-desktop": "40px",
        "stack-xl": "64px",
        "stack-sm": "8px",
        unit: "8px",
        "container-margin-mobile": "20px",
        "stack-lg": "32px",
      },
      fontFamily: {
        "headline-lg": ['"Source Serif 4"', "serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "display-lg": ['"Source Serif 4"', "serif"],
        "headline-lg-mobile": ['"Source Serif 4"', "serif"],
        "headline-md": ['"Source Serif 4"', "serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "600" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      keyframes: {
        "scan-pulse": {
          "0%, 100%": {
            borderColor: "rgba(167, 52, 0, 0.3)",
            boxShadow: "inset 0 0 0 0 rgba(167, 52, 0, 0)",
          },
          "50%": {
            borderColor: "rgba(167, 52, 0, 0.8)",
            boxShadow: "inset 0 0 20px 0 rgba(167, 52, 0, 0.2)",
          },
        },
        "scan-line": {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100%)" },
        },
        "slide-up-fade": {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "10%, 90%": { transform: "translateY(0)", opacity: "1" },
          "100%": { transform: "translateY(20px)", opacity: "0" },
        },
      },
      animation: {
        "scan-pulse": "scan-pulse 2s ease-in-out infinite",
        "scan-line": "scan-line 2.5s linear infinite",
        "slide-up-fade": "slide-up-fade 4s forwards",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
